# Generated by Django 5.2.4 on 2025-07-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_created=True)),
                ('id_alerta', models.CharField(editable=False, max_length=32, unique=True)),
                ('contexto', models.TextField()),
                ('tipo', models.CharField(max_length=50)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
    ]
