# Generated by Django 5.2.4 on 2025-07-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
