# Generated by Django 5.2.4 on 2025-07-29 09:41

import publicaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='id_publicacion',
            field=models.CharField(default=publicaciones.models.generate_uuid_hex, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
