# Generated by Django 5.2.4 on 2025-07-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_created=True)),
                ('fecha', models.DateTimeField(auto_created=True)),
                ('id_cita', models.CharField(editable=False, max_length=32, unique=True)),
                ('contexto', models.TextField()),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='programada', max_length=20)),
            ],
        ),
    ]
