# Generated by Django 5.2.4 on 2025-07-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='citas',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
